### ISSUE TITLE
Low speed and out of memory running the full AMWG setting on mac

### ISSUE THREAD

**Issue by chengzhuzhang** [zshaheen/acme_diags#32]
Need to 1. locate hotpots and optimize the codes. 2 implement multi-processes

**Comment by chengzhuzhang** [comment]
Memory profiling compare vcs backend and cartopy backend:
**1 vcs:**
Filename: set5_driver.py

Line #    Mem usage    Increment   Line Contents
================================================
    21  151.691 MiB    0.000 MiB   @profile
    22                             def make_parameters(orginal_parameter):
    23                                 """ Create multiple parameters given a list of 
    24                                 parameters in a json and an original parameter """
    25                                 #f_data = open('set5_diags_AMWG_default.json').read()
    26                                 #f_data = open('set5_diags_WHOI.json').read()
    27  151.691 MiB    0.000 MiB       f_data = open('set5_diags_HadISST.json').read()
    28  151.691 MiB    0.000 MiB       json_file = json.loads(f_data)
    29                             
    30  151.691 MiB    0.000 MiB       parameters = []
    31  151.691 MiB    0.000 MiB       for key in json_file:
    32  151.691 MiB    0.000 MiB           for single_run in json_file[key]:
    33                                         #p = copy.deepcopy(orginal_parameter)
    34  151.691 MiB    0.000 MiB               p = ACMEParameter()
    35  151.691 MiB    0.000 MiB               for attr_name in single_run:
    36  151.691 MiB    0.000 MiB                   setattr(p, attr_name, single_run[attr_name])
    37                                         # Add attributes of original_parameter to p
    38  151.691 MiB    0.000 MiB               print orginal_parameter.__dict__
    39  151.691 MiB    0.000 MiB               p.__dict__.update(orginal_parameter.__dict__)
    40  151.691 MiB    0.000 MiB               parameters.append(p)
    41  151.691 MiB    0.000 MiB       return parameters


Filename: set5_driver.py

Line #    Mem usage    Increment   Line Contents
================================================
    44 1272.426 MiB    0.000 MiB   @profile
    45                             def regrid_to_lower_res(mv1, mv2, regrid_tool, regrid_method):
    46                                 """regrid transient variable toward lower resolution of two variables"""
    47                             
    48 1272.426 MiB    0.000 MiB       axes1 = mv1.getAxisList()
    49 1272.426 MiB    0.000 MiB       axes2 = mv2.getAxisList()
    50                             
    51 1272.426 MiB    0.000 MiB       if len(axes1[1]) <= len(axes2[1]): # use nlat to decide data resolution, higher number means higher data resolution. For the difference plot, regrid toward lower resolution
    52 1272.426 MiB    0.000 MiB           mv_grid = mv1.getGrid()
    53 1272.426 MiB    0.000 MiB           mv1_reg = mv1
    54 1262.551 MiB   -9.875 MiB           mv2_reg = mv2.regrid(mv_grid, regridTool=regrid_tool, regridMethod=regrid_method)
    55                                 else:
    56                                     mv_grid = mv2.getGrid()
    57                                     mv2_reg = mv2
    58                                     mv1_reg = mv1.regrid(mv_grid, regridTool=regrid_tool, regridMethod=regrid_method)
    59 1262.551 MiB    0.000 MiB       return mv1_reg, mv2_reg


Filename: set5_driver.py

Line #    Mem usage    Increment   Line Contents
================================================
    61 1261.820 MiB    0.000 MiB   @profile
    62                             def create_metrics(ref, test, ref_regrid, test_regrid, diff):
    63                                 """ Creates the mean, max, min, rmse, corr in a dictionary """
    64 1261.820 MiB    0.000 MiB       metrics_dict = {}
    65 1261.820 MiB    0.000 MiB       metrics_dict['ref'] = {
    66 1261.820 MiB    0.000 MiB           'min': min_cdms(ref),
    67 1261.820 MiB    0.000 MiB           'max': max_cdms(ref),
    68 1262.348 MiB    0.527 MiB           'mean': mean(ref)
    69                                 }
    70 1262.348 MiB    0.000 MiB       metrics_dict['test'] = {
    71 1262.348 MiB    0.000 MiB           'min': min_cdms(test),
    72 1262.348 MiB    0.000 MiB           'max': max_cdms(test),
    73 1262.633 MiB    0.285 MiB           'mean': mean(test)
    74                                 }
    75                             
    76 1262.633 MiB    0.000 MiB       metrics_dict['diff'] = {
    77 1262.633 MiB    0.000 MiB           'min': min_cdms(diff),
    78 1262.633 MiB    0.000 MiB           'max': max_cdms(diff),
    79 1262.664 MiB    0.031 MiB           'mean': mean(diff)
    80                                 }
    81 1262.664 MiB    0.000 MiB       metrics_dict['misc'] = {
    82 1263.207 MiB    0.543 MiB           'rmse': rmse(test_regrid, ref_regrid),
    83 1263.367 MiB    0.160 MiB           'corr': corr(test_regrid, ref_regrid)
    84                                 }
    85                             
    86 1263.367 MiB    0.000 MiB       return metrics_dict

**2. cartopy**
Filename: set5_driver.py

Line #    Mem usage    Increment   Line Contents
================================================
    21  154.379 MiB    0.000 MiB   @profile
    22                             def make_parameters(orginal_parameter):
    23                                 """ Create multiple parameters given a list of 
    24                                 parameters in a json and an original parameter """
    25                                 #f_data = open('set5_diags_AMWG_default.json').read()
    26                                 #f_data = open('set5_diags_WHOI.json').read()
    27  154.379 MiB    0.000 MiB       f_data = open('set5_diags_HadISST.json').read()
    28  154.379 MiB    0.000 MiB       json_file = json.loads(f_data)
    29                             
    30  154.379 MiB    0.000 MiB       parameters = []
    31  154.379 MiB    0.000 MiB       for key in json_file:
    32  154.379 MiB    0.000 MiB           for single_run in json_file[key]:
    33                                         #p = copy.deepcopy(orginal_parameter)
    34  154.379 MiB    0.000 MiB               p = ACMEParameter()
    35  154.379 MiB    0.000 MiB               for attr_name in single_run:
    36  154.379 MiB    0.000 MiB                   setattr(p, attr_name, single_run[attr_name])
    37                                         # Add attributes of original_parameter to p
    38  154.379 MiB    0.000 MiB               print orginal_parameter.__dict__
    39  154.379 MiB    0.000 MiB               p.__dict__.update(orginal_parameter.__dict__)
    40  154.379 MiB    0.000 MiB               parameters.append(p)
    41  154.379 MiB    0.000 MiB       return parameters


Filename: set5_driver.py

Line #    Mem usage    Increment   Line Contents
================================================
    44  433.828 MiB    0.000 MiB   @profile
    45                             def regrid_to_lower_res(mv1, mv2, regrid_tool, regrid_method):
    46                                 """regrid transient variable toward lower resolution of two variables"""
    47                             
    48  433.828 MiB    0.000 MiB       axes1 = mv1.getAxisList()
    49  433.828 MiB    0.000 MiB       axes2 = mv2.getAxisList()
    50                             
    51  433.828 MiB    0.000 MiB       if len(axes1[1]) <= len(axes2[1]): # use nlat to decide data resolution, higher number means higher data resolution. For the difference plot, regrid toward lower resolution
    52  433.828 MiB    0.000 MiB           mv_grid = mv1.getGrid()
    53  433.828 MiB    0.000 MiB           mv1_reg = mv1
    54  437.246 MiB    3.418 MiB           mv2_reg = mv2.regrid(mv_grid, regridTool=regrid_tool, regridMethod=regrid_method)
    55                                 else:
    56                                     mv_grid = mv2.getGrid()
    57                                     mv2_reg = mv2
    58                                     mv1_reg = mv1.regrid(mv_grid, regridTool=regrid_tool, regridMethod=regrid_method)
    59  437.246 MiB    0.000 MiB       return mv1_reg, mv2_reg


Filename: set5_driver.py

Line #    Mem usage    Increment   Line Contents
================================================
    61  436.684 MiB    0.000 MiB   @profile
    62                             def create_metrics(ref, test, ref_regrid, test_regrid, diff):
    63                                 """ Creates the mean, max, min, rmse, corr in a dictionary """
    64  436.684 MiB    0.000 MiB       metrics_dict = {}
    65  436.684 MiB    0.000 MiB       metrics_dict['ref'] = {
    66  436.684 MiB    0.000 MiB           'min': min_cdms(ref),
    67  436.684 MiB    0.000 MiB           'max': max_cdms(ref),
    68  437.359 MiB    0.676 MiB           'mean': mean(ref)
    69                                 }
    70  437.359 MiB    0.000 MiB       metrics_dict['test'] = {
    71  437.359 MiB    0.000 MiB           'min': min_cdms(test),
    72  437.359 MiB    0.000 MiB           'max': max_cdms(test),
    73  437.645 MiB    0.285 MiB           'mean': mean(test)
    74                                 }
    75                             
    76  437.645 MiB    0.000 MiB       metrics_dict['diff'] = {
    77  437.645 MiB    0.000 MiB           'min': min_cdms(diff),
    78  437.645 MiB    0.000 MiB           'max': max_cdms(diff),
    79  437.676 MiB    0.031 MiB           'mean': mean(diff)
    80                                 }
    81  437.676 MiB    0.000 MiB       metrics_dict['misc'] = {
    82  438.059 MiB    0.383 MiB           'rmse': rmse(test_regrid, ref_regrid),
    83  438.223 MiB    0.164 MiB           'corr': corr(test_regrid, ref_regrid)
    84                                 }
    85                             
    86  438.223 MiB    0.000 MiB       return metrics_dict

**Comment by chengzhuzhang** [comment]
@zshaheen 
Approximate time test for the whole AMWG set5 obs. on my macbook air. (not sure if have memory profilor on could slow things..)
 with cartopy.
Real 54m
User 47m
Sys 5m

For vcs backend, program ran for a whole day and some night time to cover about half of the variables, laptop crashes with out of memory.

**Comment by zshaheen** [comment]
@chengzhuzhang 
I'm pretty sure the vcs memory problems are caused by repeatedly calling `vcs.init()`. But I'm not sure if these diagnostics are meant to be ran on laptops with ~8GB of memory, running on aims2 or aims4 would 'fix' the memory problem.

I also think we can make vcs faster if it doesn't display the output image after each run, and just write to file. I'll work on this.

On Monday, I'll run cProfile and line_profiler and see what takes the longest in terms of time.

**Comment by chengzhuzhang** [comment]
@zshaheen These are good points! Thanks. Another possibility is that many variables are calculated more than once, if we can reduce the repetition probably can also help the speed up...

**Comment by zshaheen** [comment]
@chengzhuzhang Yes, that's where the caching comes into play. And for that to be re-enabled, Denis and I will have to get the cdms provenance working.

**Comment by chengzhuzhang** [comment]
Speed is 7 x faster with combined text cached.
