### ISSUE TITLE
HadISST only shows result from one run in viewer

### ISSUE THREAD

**Issue by chengzhuzhang** [zshaheen/acme_diags#65]

**Comment by zshaheen** [comment]
@chengzhuzhang Did you get the latest code from master? Because I had this issue, but 2b0bed32cc3e846608c6865aabbb469e015ebd66 fixed it.

**Comment by chengzhuzhang** [comment]
@zshaheen I have the latest code. it problem also occurs for set3. I think three plots are generated in acme_diags/set3/set3/set3_SST_HadISST, however not in set-3 folder...

**Comment by zshaheen** [comment]
@chengzhuzhang If you still have the folders, can you compress it and send it to me? If not, that's okay.

**Comment by zshaheen** [comment]
Thanks @chengzhuzhang
